---

- name: install yum-utils
  yum:
    name: yum-utils
    state: present
    update_cache: yes

- name: add in yum repo
  yum_repository:
    name: docker-ce
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo

- name: install docker_packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ centos_remove_packages }}"

