---

- name: install ca-certificates and other packages
  block:
    - name: "for CentOS"
      include_tasks: centos7.yml
      when: ansible_os_family == "CentOS" and ansible_pkg_mgr == "yum"

    - name: "for Ubuntu"
      include_tasks: ubuntu20_04.yml
      when: ansible_os_family == "Debian" and ansible_pkg_mgr == "apt"
