---

- name: make directory
  block:
    - name: make a dir
      file:
        path: "{{ item.dir }}"
        state: directory

    - name: copying zabbix-server file
      include_tasks: zabbix_package/docker-compose-server-amd64.yaml
      when: "'zabbix_server' in inventory_hostname"

    - name: copying zabbix-proxy file
      include_tasks: zabbix_package/docker-compose-proxy-amd64.yaml
      when: "'zabbix_server' in inventory_hostname"






